-- Import der von ChatGPT Codex recherchierten Münchner Klassik-Stammdaten
-- (Künstler:innen, Ensembles, Venues, Institutionen), Stand 2026-07-20.
-- ACHTUNG vor dem Anwenden:
--  * photo_url/gallery_urls werden bewusst NICHT gesetzt: die Quelldatei liefert nur
--    eine Wikimedia-Commons-Suchseite bzw. die Website als Referenz, keine echte
--    Bild-URL, und verlangt selbst eine Lizenzprüfung vor Verwendung. Kuratierung
--    folgt separat (Admin-Plattform).
--  * is_verified = false für alle neuen Zeilen -- redaktionelle Freigabe aussteht.
--  * roles/ensemble_type wurden aus dem Freitext 'role_or_type' heuristisch abgeleitet
--    (Substring-Matching) -- bei Bedarf nach Review anpassen.
--  * venues.location wurde via OpenStreetMap/Nominatim aus der Adresse geokodiert --
--    ungeprüfte Drittquelle, vor produktivem Einsatz stichprobenartig verifizieren.

-- ===== Personen (category=artist) =====
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Anja%20Harteros%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('anja-harteros', 'Anja Harteros', array['solist']::participant_role[], 'International gefeierte Sopranistin; prägte über viele Jahre zentrale Rollen an der Bayerischen Staatsoper.', '1972-01-01', 'https://www.anjaharteros.de/', false);
-- Quelle: https://www.arabella-steinbacher.com/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Arabella%20Steinbacher%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('arabella-steinbacher', 'Arabella Steinbacher', array['solist']::participant_role[], 'In München geborene Violinistin mit internationaler Solokarriere.', '1981-01-01', 'https://www.arabella-steinbacher.com/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Brigitte%20Fassbaender%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('brigitte-fassbaender', 'Brigitte Fassbaender', array['solist']::participant_role[], 'Mezzosopranistin, Regisseurin und frühere Intendantin des Tiroler Landestheaters; langjähriges Ensemblemitglied der Staatsoper.', '1939-01-01', 'https://www.brigitte-fassbaender.de/', false);
-- Quelle: https://www.orff.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Carl%20Orff%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('carl-orff', 'Carl Orff', array['komponist']::participant_role[], 'Komponist und Pädagoge, Schöpfer des Orff-Schulwerks; lebte und wirkte lange in München.', '1895-01-01', 'https://www.orff.de/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Carlos%20Kleiber%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('carlos-kleiber', 'Carlos Kleiber', array['dirigent']::participant_role[], 'Legendärer Dirigent, eng mit dem Bayerischen Staatsorchester und dem Nationaltheater verbunden.', '1930-01-01', null, false);
-- Quelle: https://www.christiangerhaher.com/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Christian%20Gerhaher%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('christian-gerhaher', 'Christian Gerhaher', array['solist']::participant_role[], 'Bariton und Liedinterpret von internationalem Rang, in Straubing geboren und in München ausgebildet.', '1969-01-01', 'https://www.christiangerhaher.com/', false);
-- Quelle: https://www.mphil.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Christian%20Thielemann%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('christian-thielemann', 'Christian Thielemann', array['dirigent']::participant_role[], 'Dirigent; war von 2004 bis 2011 Generalmusikdirektor der Münchner Philharmoniker.', '1959-01-01', 'https://www.mphil.de/', false);
-- Quelle: https://www.diana-damrau.com/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Diana%20Damrau%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('diana-damrau', 'Diana Damrau', array['solist']::participant_role[], 'Koloratursopranistin von internationalem Rang, an der Hochschule für Musik und Theater München ausgebildet.', '1971-01-01', 'https://www.diana-damrau.com/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Edita%20Gruberov%C3%A1%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('edita-gruberova', 'Edita Gruberová', array['solist']::participant_role[], 'Sopranistin und langjähriges Mitglied der Bayerischen Staatsoper, besonders im Belcanto-Repertoire prägend.', '1946-01-01', null, false);
-- Quelle: https://www.brso.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Eugen%20Jochum%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('eugen-jochum', 'Eugen Jochum', array['dirigent']::participant_role[], 'Dirigent; leitete 1949 bis 1960 das Symphonieorchester des Bayerischen Rundfunks.', '1902-01-01', null, false);
-- Quelle: https://www.deutsche-biographie.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Franz%20Lachner%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('franz-lachner', 'Franz Lachner', array['dirigent','komponist']::participant_role[], 'Komponist und Dirigent; von 1836 bis 1867 Hofkapellmeister in München.', '1803-01-01', null, false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Gerold%20Huber%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('gerold-huber', 'Gerold Huber', array['solist']::participant_role[], 'Pianist und Liedbegleiter; Professor an der Hochschule für Musik und Theater München.', '1969-01-01', 'https://www.geroldhuber.de/', false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Igor%20Levit%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('igor-levit', 'Igor Levit', array['solist']::participant_role[], 'Pianist, der an der Hochschule für Musik und Theater München studierte.', '1987-01-01', 'https://www.igorlevit.de/', false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Julia%20Fischer%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('julia-fischer', 'Julia Fischer', array['solist']::participant_role[], 'In München geborene Violinistin und Professorin an der Hochschule für Musik und Theater München.', '1983-01-01', 'https://www.juliafischer.com/', false);
-- Quelle: https://www.julianpregardien.com/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Julian%20Pr%C3%A9gardien%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('julian-pregardien', 'Julian Prégardien', array['solist']::participant_role[], 'Tenor und Liedsänger aus einer Münchner Sängerfamilie.', '1984-01-01', 'https://www.julianpregardien.com/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Kent%20Nagano%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('kent-nagano', 'Kent Nagano', array['dirigent']::participant_role[], 'Dirigent; Generalmusikdirektor der Bayerischen Staatsoper von 2006 bis 2013.', '1951-01-01', 'https://www.kentnagano.com/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Kirill%20Petrenko%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('kirill-petrenko', 'Kirill Petrenko', array['dirigent']::participant_role[], 'Dirigent; Generalmusikdirektor der Bayerischen Staatsoper von 2013 bis 2018.', '1972-01-01', null, false);
-- Quelle: https://www.mphil.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Lahav%20Shani%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('lahav-shani', 'Lahav Shani', array['dirigent']::participant_role[], 'Dirigent und designierter Chefdirigent des Münchner Philharmoniker ab der Saison 2026/27.', '1989-01-01', 'https://www.mphil.de/', false);
-- Quelle: https://www.brso.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Mariss%20Jansons%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('mariss-jansons', 'Mariss Jansons', array['dirigent']::participant_role[], 'Dirigent; Chefdirigent des Symphonieorchesters des Bayerischen Rundfunks von 2003 bis 2019.', '1943-01-01', null, false);
-- Quelle: https://www.richard-strauss-institut.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Richard%20Strauss%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('richard-strauss', 'Richard Strauss', array['dirigent','komponist']::participant_role[], 'Komponist und Dirigent, in München geboren; wichtige Werke wurden hier uraufgeführt.', '1864-01-01', null, false);
-- Quelle: https://www.mphil.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Sergiu%20Celibidache%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('sergiu-celibidache', 'Sergiu Celibidache', array['dirigent']::participant_role[], 'Dirigent; Generalmusikdirektor der Münchner Philharmoniker von 1979 bis 1996.', '1912-01-01', null, false);
-- Quelle: https://www.brso.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Sir%20Simon%20Rattle%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('sir-simon-rattle', 'Sir Simon Rattle', array['dirigent']::participant_role[], 'Dirigent und künstlerischer Leiter des Symphonieorchesters des Bayerischen Rundfunks seit 2023.', '1955-01-01', 'https://www.brso.de/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Vladimir%20Jurowski%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('vladimir-jurowski', 'Vladimir Jurowski', array['dirigent']::participant_role[], 'Dirigent; Generalmusikdirektor der Bayerischen Staatsoper seit der Spielzeit 2021/22.', '1972-01-01', 'https://www.staatsoper.de/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Waltraud%20Meier%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('waltraud-meier', 'Waltraud Meier', array['solist']::participant_role[], 'Mezzosopranistin und Sopranistin, eng mit der Bayerischen Staatsoper verbunden.', '1956-01-01', 'https://www.waltraud-meier.com/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Wolfgang%20Sawallisch%20M%C3%BCnchen
insert into persons (slug, full_name, roles, biography_de, birth_date, website_url, is_verified) values ('wolfgang-sawallisch', 'Wolfgang Sawallisch', array['dirigent']::participant_role[], 'Dirigent; Generalmusikdirektor der Bayerischen Staatsoper von 1971 bis 1992.', '1923-01-01', null, false);

-- ===== Ensembles (category=ensemble) =====
-- Quelle: https://www.arcis-vocalisten.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Arcis-Vocalisten%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('arcis-vocalisten-muenchen', 'Arcis-Vocalisten München', 'chor', 'Semiprofessioneller Chor für Konzert- und Oratorienrepertoire vom Frühbarock bis zur Gegenwart.', 'https://www.arcis-vocalisten.de/', false);
-- Quelle: https://www.staatsballett.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Bayerisches%20Staatsballett%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('bayerisches-staatsballett', 'Bayerisches Staatsballett', 'sonstiges', 'Ballettcompagnie der Bayerischen Staatsoper mit eigenem Repertoire und Orchesterbezug.', 'https://www.staatsballett.de/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Bayerisches%20Staatsorchester%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('bayerisches-staatsorchester', 'Bayerisches Staatsorchester', 'orchester', 'Orchester der Bayerischen Staatsoper; eines der ältesten kontinuierlich bestehenden Orchester.', 'https://www.staatsoper.de/', false);
-- Quelle: https://www.br.de/br-chor/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Chor%20des%20Bayerischen%20Rundfunks%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('chor-des-bayerischen-rundfunks', 'Chor des Bayerischen Rundfunks', 'chor', 'Professioneller Konzertchor des Bayerischen Rundfunks.', 'https://www.br.de/br-chor/', false);
-- Quelle: https://www.concerto-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Concerto%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('concerto-muenchen', 'Concerto München', 'sonstiges', 'Ensemble für historische Aufführungspraxis mit Schwerpunkt Barock und Klassik.', 'https://www.concerto-muenchen.de/', false);
-- Quelle: https://www.hofkapelle-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Hofkapelle%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('hofkapelle-muenchen', 'Hofkapelle München', 'sonstiges', 'Barockorchester und Chor, spezialisiert auf historisch informierte Aufführungspraxis.', 'https://www.hofkapelle-muenchen.de/', false);
-- Quelle: https://klassikchormuenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Klassik%20Chor%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('klassik-chor-muenchen', 'Klassik Chor München', 'chor', 'Unabhängiger Chor für geistliche und weltliche Vokalmusik von der frühen Musik bis zur Gegenwart.', 'https://klassikchormuenchen.de/', false);
-- Quelle: https://www.labandamuenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=La%20Banda%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('la-banda', 'La Banda', 'orchester', 'Münchner Barockorchester auf historischen Instrumenten.', 'https://www.labandamuenchen.de/', false);
-- Quelle: https://www.lafestamusicale.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=La%20Festa%20Musicale%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('la-festa-musicale', 'La Festa Musicale', 'sonstiges', 'Vokal- und Instrumentalensemble für Alte Musik mit Sitz in München.', 'https://www.lafestamusicale.de/', false);
-- Quelle: https://www.muenchener-bachchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchener%20Bach-Chor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchener-bach-chor', 'Münchener Bach-Chor', 'chor', 'Großer Konzertchor, 1954 von Karl Richter gegründet.', 'https://www.muenchener-bachchor.de/', false);
-- Quelle: https://www.muenchener-bachchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchener%20Bach-Orchester%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchener-bach-orchester', 'Münchener Bach-Orchester', 'orchester', 'Orchester für Barock, Klassik und Oratorienrepertoire, eng mit dem Münchener Bach-Chor verbunden.', 'https://www.muenchener-bachchor.de/', false);
-- Quelle: https://www.m-k-o.eu/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchener%20Kammerorchester%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchener-kammerorchester', 'Münchener Kammerorchester', 'orchester', 'Internationales Kammerorchester mit Repertoire von Barock bis Gegenwart.', 'https://www.m-k-o.eu/', false);
-- Quelle: https://www.muenchenklang.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchenKlang%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchenklang', 'MünchenKlang', 'sonstiges', 'Junges Ensemble aus Chor und Orchester für klassisches Chor- und Orchesterrepertoire.', 'https://www.muenchenklang.de/', false);
-- Quelle: https://www.muenchner-dommusik.de/choere/domchor-muenchen/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Domchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-domchor', 'Münchner Domchor', 'chor', 'Gemischter Kathedralchor der Münchner Dommusik mit rund 70 erwachsenen Sängerinnen und Sängern.', 'https://www.muenchner-dommusik.de/', false);
-- Quelle: https://www.muenchner-dommusik.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Domsingknaben%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-domsingknaben', 'Münchner Domsingknaben', 'chor', 'Knabenchor der Münchner Dommusik mit liturgischem und konzertantem Repertoire.', 'https://www.muenchner-dommusik.de/', false);
-- Quelle: https://www.muenchner-kammerchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Kammerchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-kammerchor', 'Münchner Kammerchor', 'chor', 'Professioneller Kammerchor mit Schwerpunkt auf A-cappella-Repertoire und Neuer Musik.', 'https://www.muenchner-kammerchor.de/', false);
-- Quelle: https://www.muenchnerknabenchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Knabenchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-knabenchor', 'Münchner Knabenchor', 'chor', 'Knabenchor mit professioneller Gesangsausbildung und internationaler Konzert- und Operntätigkeit.', 'https://www.muenchnerknabenchor.de/', false);
-- Quelle: https://muenchner-konzertchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Konzertchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-konzertchor', 'Münchner Konzertchor', 'chor', 'Konzertchor mit rund 80 Sängerinnen und Sängern und geistlichem wie weltlichem Repertoire.', 'https://muenchner-konzertchor.de/', false);
-- Quelle: https://www.muenchner-dommusik.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20M%C3%A4dchenkantorei%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-maedchenkantorei', 'Münchner Mädchenkantorei', 'chor', 'Mädchenchor der Münchner Dommusik für Liturgie, Konzert und Nachwuchsförderung.', 'https://www.muenchner-dommusik.de/', false);
-- Quelle: https://www.muenchner-madrigalchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Madrigalchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-madrigalchor', 'Münchner Madrigalchor', 'chor', 'Gemischter Chor mit Schwerpunkt auf anspruchsvoller A-cappella-Musik und Kammerchorrepertoire.', 'https://www.muenchner-madrigalchor.de/', false);
-- Quelle: https://www.muenchneroratorienchor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Oratorienchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-oratorienchor', 'Münchner Oratorienchor', 'chor', 'Konzertchor für große chorsinfonische Werke von der Barockzeit bis zur Gegenwart.', 'https://www.muenchneroratorienchor.de/', false);
-- Quelle: https://www.br.de/muenchner-rundfunkorchester/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Rundfunkorchester%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-rundfunkorchester', 'Münchner Rundfunkorchester', 'orchester', 'Orchester des Bayerischen Rundfunks mit breitem Repertoire von Oper bis Filmmusik.', 'https://www.br.de/muenchner-rundfunkorchester/', false);
-- Quelle: https://www.muenchner-symphoniker.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Symphoniker%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('muenchner-symphoniker', 'Münchner Symphoniker', 'orchester', 'Sinfonieorchester mit Konzertreihen, Filmaufnahmen und Bildungsarbeit.', 'https://www.muenchner-symphoniker.de/', false);
-- Quelle: https://www.theaterakademie.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Orchester%20der%20Theaterakademie%20August%20Everding%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('orchester-der-theaterakademie-august-everding', 'Orchester der Theaterakademie August Everding', 'orchester', 'Projektorchester der Theaterakademie für Opernproduktionen des Nachwuchses.', 'https://www.theaterakademie.de/', false);
-- Quelle: https://www.gaertnerplatztheater.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Orchester%20des%20Staatstheaters%20am%20G%C3%A4rtnerplatz%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('orchester-des-staatstheaters-am-gaertnerplatz', 'Orchester des Staatstheaters am Gärtnerplatz', 'orchester', 'Hausorchester des Staatstheaters am Gärtnerplatz.', 'https://www.gaertnerplatztheater.de/', false);
-- Quelle: https://www.philharmonischer-chor-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Philharmonischer%20Chor%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('philharmonischer-chor-muenchen', 'Philharmonischer Chor München', 'chor', 'Konzertchor, der regelmäßig mit den Münchner Philharmonikern und anderen Orchestern arbeitet.', 'https://www.philharmonischer-chor-muenchen.de/', false);
-- Quelle: https://www.chor-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=SebastiansChor%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('sebastianschor-muenchen', 'SebastiansChor München', 'chor', 'Freier Chorverein mit geistlichem und klassischem Konzertrepertoire.', 'https://www.chor-muenchen.de/', false);
-- Quelle: https://www.brso.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Symphonieorchester%20des%20Bayerischen%20Rundfunks%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('symphonieorchester-des-bayerischen-rundfunks', 'Symphonieorchester des Bayerischen Rundfunks', 'orchester', 'Sinfonieorchester des Bayerischen Rundfunks mit internationaler Konzerttätigkeit.', 'https://www.brso.de/', false);
-- Quelle: https://www.toelzerknabenchor.de/kontakt  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=T%C3%B6lzer%20Knabenchor%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('toelzer-knabenchor', 'Tölzer Knabenchor', 'chor', 'International bekannter Knabenchor mit Münchner Großraumbezug und klassischem Konzert-, Opern- und Oratorienrepertoire.', 'https://www.toelzerknabenchor.de/', false);
-- Quelle: https://www.via-nova-chor.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=via-nova-chor%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('via-nova-chor-muenchen', 'via-nova-chor München', 'chor', 'Konzertchor mit Schwerpunkt auf zeitgenössischer Chormusik.', 'https://www.via-nova-chor.de/', false);
-- Quelle: https://www.vocalensemble-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Vocalensemble%20M%C3%BCnchen%20M%C3%BCnchen
insert into ensembles (slug, name, type, description_de, website_url, is_verified) values ('vocalensemble-muenchen', 'Vocalensemble München', 'chor', 'Professioneller Kammerchor mit Schwerpunkt auf Alter und Neuer Musik.', 'https://www.vocalensemble-muenchen.de/', false);

-- ===== Venues (category=venue) =====
-- Quelle: https://www.pinakothek.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Alte%20Pinakothek%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('alte-pinakothek', 'Alte Pinakothek', 'Kunstmuseum mit Konzertformaten und klassisch geprägten Sonderveranstaltungen.', 'Barer Straße 27', '80333', 'München', ST_MakePoint(11.5699796, 48.1482838)::geography, 'https://www.pinakothek.de/', false);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Black%20Box%20im%20Gasteig%20HP8%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('black-box-im-gasteig-hp8', 'Black Box im Gasteig HP8', 'Flexibler Saal am Gasteig-Interimsstandort für kleinere Konzert- und Veranstaltungsformate.', 'Hans-Preißinger-Straße 8', '81379', 'München', ST_MakePoint(11.553687, 48.1114407)::geography, 'https://www.gasteig.de/', false);
-- Quelle: https://www.buergersaal.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=B%C3%BCrgersaal%20M%C3%BCnchen%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('buergersaal-muenchen', 'Bürgersaal München', 'Barocker Kirchenraum der Marianischen Männer-Congregation mit Kirchenmusikprogramm.', 'Neuhauser Straße 14', '80333', 'München', ST_MakePoint(11.5682512, 48.1390184)::geography, 'https://www.buergersaal.de/', false);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Carl-Orff-Saal%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('carl-orff-saal', 'Carl-Orff-Saal', 'Konzertsaal im ursprünglichen Gasteig-Gebäude am Rosenheimer Platz; derzeit sanierungsbedingt nicht regulär bespielt.', 'Rosenheimer Straße 5', '81667', 'München', ST_MakePoint(11.5906675, 48.131765)::geography, 'https://www.gasteig.de/', false);
-- Quelle: https://www.schloesser.bayern.de/deutsch/residenz/muenchen/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Cuvilli%C3%A9s-Theater%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('cuvillies-theater', 'Cuvilliés-Theater', 'Rokokotheater der Residenz; historische Opern- und Konzertspielstätte.', 'Residenzstraße 1', '80539', 'München', ST_MakePoint(11.5778676, 48.1421714)::geography, 'https://www.schloesser.bayern.de/deutsch/residenz/muenchen/', false);
-- Quelle: https://www.deutsches-theater.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Deutsches%20Theater%20M%C3%BCnchen%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('deutsches-theater-muenchen', 'Deutsches Theater München', 'Großes Gastspieltheater, das auch klassische Konzerte und Musiktheater zeigt.', 'Schwanthalerstraße 13', '80336', 'München', ST_MakePoint(11.5620425, 48.1368977)::geography, 'https://www.deutsches-theater.de/', false);
-- Quelle: https://www.muenchner-dommusik.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Dom%20zu%20Unserer%20Lieben%20Frau%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('dom-zu-unserer-lieben-frau', 'Dom zu Unserer Lieben Frau', 'Kathedrale des Erzbistums München und Freising mit Dommusik, Orgel- und Chorkonzerten.', 'Frauenplatz 12', '80331', 'München', ST_MakePoint(11.5743388, 48.1388679)::geography, 'https://www.muenchner-dom.de/', false);
-- Quelle: https://www.erloeserkirche.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Erl%C3%B6serkirche%20Schwabing%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('erloeserkirche-schwabing', 'Erlöserkirche Schwabing', 'Evangelische Kirche mit regelmäßiger Kirchenmusik und Konzertreihen.', 'Ungererstraße 17', '80802', 'München', ST_MakePoint(11.5882549, 48.1650568)::geography, 'https://www.erloeserkirche.de/', false);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Gasteig%20am%20Rosenheimer%20Platz%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('gasteig-am-rosenheimer-platz', 'Gasteig am Rosenheimer Platz', 'Kulturzentrum am Rosenheimer Platz; während der Sanierung im Interim.', 'Rosenheimer Straße 5', '81667', 'München', ST_MakePoint(11.5906675, 48.131765)::geography, 'https://www.gasteig.de/', false);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Gasteig%20HP8%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('gasteig-hp8', 'Gasteig HP8', 'Interimsquartier des Gasteig mit mehreren Sälen, Proben- und Veranstaltungsräumen.', 'Hans-Preißinger-Straße 8', '81379', 'München', ST_MakePoint(11.553687, 48.1114407)::geography, 'https://www.gasteig.de/', false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Gro%C3%9Fer%20Konzertsaal%20der%20HMTM%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('grosser-konzertsaal-der-hmtm', 'Großer Konzertsaal der HMTM', 'Hauptkonzertsaal der Hochschule für Musik und Theater München.', 'Arcisstraße 12', '80333', 'München', ST_MakePoint(11.5674452, 48.1460982)::geography, 'https://hmtm.de/', false);
-- Quelle: https://www.heilig-geist-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Heilig-Geist-Kirche%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('heilig-geist-kirche', 'Heilig-Geist-Kirche', 'Barocke Pfarrkirche am Viktualienmarkt mit Kirchenmusik und Orgelkonzerten.', 'Prälat-Miller-Weg 1', '80331', 'München', ST_MakePoint(11.5773584, 48.1362008)::geography, 'https://www.heilig-geist-muenchen.de/', false);
-- Quelle: https://www.erzbistum-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Herz-Jesu-Kirche%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('herz-jesu-kirche', 'Herz-Jesu-Kirche', 'Moderne katholische Kirche mit prägnanter Architektur und regelmäßigem Konzertprogramm.', 'Lachnerstraße 8', '80639', 'München', ST_MakePoint(11.5288802, 48.1561747)::geography, 'https://www.erzbistum-muenchen.de/pfarrei/pv-neuhausen/cont/70546', false);
-- Quelle: https://www.himmelfahrtskirche-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Himmelfahrtskirche%20Sendling%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('himmelfahrtskirche-sendling', 'Himmelfahrtskirche Sendling', 'Evangelische Kirche mit etablierter Konzert- und Kirchenmusikarbeit.', 'Kidlerstraße 15', '81371', 'München', ST_MakePoint(11.5427749, 48.120457)::geography, 'https://www.himmelfahrtskirche-muenchen.de/', false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Kleiner%20Konzertsaal%20der%20HMTM%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('kleiner-konzertsaal-der-hmtm', 'Kleiner Konzertsaal der HMTM', 'Konzertsaal der Hochschule für Musik und Theater München für Recitals und Kammermusik.', 'Arcisstraße 12', '80333', 'München', ST_MakePoint(11.5674452, 48.1460982)::geography, 'https://hmtm.de/', false);
-- Quelle: https://www.muffatwerk.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Muffathalle%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('muffathalle', 'Muffathalle', 'Ehemaliges Heizkraftwerk und Kulturzentrum; auch Spielort für zeitgenössische und klassische Musik.', 'Zellstraße 4', '81667', 'München', ST_MakePoint(11.5894533, 48.1330499)::geography, 'https://www.muffatwerk.de/', false);
-- Quelle: https://www.kuenstlerhaus-muc.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20K%C3%BCnstlerhaus%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('muenchner-kuenstlerhaus', 'Münchner Künstlerhaus', 'Historisches Kulturhaus mit Festsaal und klassischen Konzertreihen.', 'Lenbachplatz 8', '80333', 'München', ST_MakePoint(11.5678633, 48.1401245)::geography, 'https://www.kuenstlerhaus-muc.de/', false);
-- Quelle: https://www.villastuck.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Museum%20Villa%20Stuck%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('museum-villa-stuck', 'Museum Villa Stuck', 'Künstlervilla und Museum mit Kammerkonzerten und Veranstaltungsreihen.', 'Prinzregentenstraße 60', '81675', 'München', ST_MakePoint(11.5996612, 48.1404871)::geography, 'https://www.villastuck.de/', false);
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Nationaltheater%20M%C3%BCnchen%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('nationaltheater-muenchen', 'Nationaltheater München', 'Opernhaus am Max-Joseph-Platz und Hauptspielstätte der Bayerischen Staatsoper.', 'Max-Joseph-Platz 2', '80539', 'München', ST_MakePoint(11.5795133, 48.1396162)::geography, 'https://www.staatsoper.de/', false);
-- Quelle: https://www.residenztheater.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Residenztheater%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('residenztheater', 'Residenztheater', 'Schauspielhaus mit regelmäßigem Musiktheater, Lesungen und klassischer Konzertnutzung.', 'Max-Joseph-Platz 1', '80539', 'München', ST_MakePoint(11.5794332, 48.1401132)::geography, 'https://www.residenztheater.de/', false);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Saal%20X%20im%20Gasteig%20HP8%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('saal-x-im-gasteig-hp8', 'Saal X im Gasteig HP8', 'Flexibler Saal des Gasteig HP8 für Konzerte, Tanz und Musiktheater.', 'Hans-Preißinger-Straße 8', '81379', 'München', ST_MakePoint(11.553687, 48.1114407)::geography, 'https://www.gasteig.de/', false);
-- Quelle: https://www.st-anna-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Anna%20im%20Lehel%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-anna-im-lehel', 'St. Anna im Lehel', 'Kirche mit konzertanter Kirchenmusik und Orgelprogramm.', 'St.-Anna-Straße 19', '80538', 'München', ST_MakePoint(11.5855138, 48.1403926)::geography, 'https://www.st-anna-muenchen.de/', false);
-- Quelle: https://www.sankt-bonifaz.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Bonifaz%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-bonifaz', 'St. Bonifaz', 'Basilika und Abtei mit Choral, Orgelmusik und Konzertreihen.', 'Karlstraße 34', '80333', 'München', ST_MakePoint(11.5642155, 48.1440642)::geography, 'https://www.sankt-bonifaz.de/', false);
-- Quelle: https://www.st-ludwig-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Ludwig%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-ludwig', 'St. Ludwig', 'Große Universitätskirche mit bedeutender Orgel- und Kirchenmusikarbeit.', 'Ludwigstraße 20', '80539', 'München', ST_MakePoint(11.5812526, 48.1488494)::geography, 'https://www.st-ludwig-muenchen.de/', false);
-- Quelle: https://www.st-markus-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Markus%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-markus', 'St. Markus', 'Evangelische Kirche mit traditionsreicher Kirchenmusik und Konzertreihen.', 'Gabelsbergerstraße 6', '80333', 'München', ST_MakePoint(11.5743622, 48.1460981)::geography, 'https://www.st-markus-muenchen.de/', false);
-- Quelle: https://www.stmatthaeus.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Matth%C3%A4us%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-matthaeus', 'St. Matthäus', 'Evangelisch-lutherische Hauptkirche Münchens mit regelmäßigem Kirchenmusikprogramm.', 'Nußbaumstraße 1', '80336', 'München', ST_MakePoint(11.5648182, 48.1331902)::geography, 'https://www.stmatthaeus.de/', false);
-- Quelle: https://www.alterpeter.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Peter%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-peter', 'St. Peter', 'Älteste Pfarrkirche Münchens mit Kirchenmusik- und Orgelangebot.', 'Rindermarkt 1', '80331', 'München', ST_MakePoint(11.5753244, 48.1363083)::geography, 'https://www.alterpeter.de/', false);
-- Quelle: https://www.st-ursula-muenchen.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=St.%20Ursula%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('st-ursula', 'St. Ursula', 'Kirche in Schwabing mit Chor- und Orgelkonzerten.', 'Kaiserplatz 1', '80803', 'München', ST_MakePoint(11.5809035, 48.1611496)::geography, 'https://www.st-ursula-muenchen.de/', false);
-- Quelle: https://www.gaertnerplatztheater.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Staatstheater%20am%20G%C3%A4rtnerplatz%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('staatstheater-am-gaertnerplatz', 'Staatstheater am Gärtnerplatz', 'Staatstheater für Operette, Musical, Tanz und Oper mit festem Ensemble und Orchester.', 'Gärtnerplatz 3', '80469', 'München', ST_MakePoint(11.5755063, 48.1310822)::geography, 'https://www.gaertnerplatztheater.de/', false);
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Theaterakademie%20August%20Everding%20%E2%80%93%20Opernschule%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('theaterakademie-august-everding-opernschule', 'Theaterakademie August Everding – Opernschule', 'Ausbildungs- und Aufführungsort der HMTM und Theaterakademie im Prinzregententheater.', 'Prinzregentenplatz 12', '81675', 'München', ST_MakePoint(11.6056214, 48.1389662)::geography, 'https://hmtm.de/', false);
-- Quelle: https://www.theatinerkirche.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Theatinerkirche%20St.%20Kajetan%20M%C3%BCnchen
insert into venues (slug, name, description_de, address_street, address_zip, address_city, location, website_url, is_verified) values ('theatinerkirche-st-kajetan', 'Theatinerkirche St. Kajetan', 'Barockkirche am Odeonsplatz mit Kirchenmusik und konzertanten Aufführungen.', 'Theatinerstraße 22', '80333', 'München', ST_MakePoint(11.5766146, 48.1420299)::geography, 'https://www.theatinerkirche.de/', false);

-- ===== Organizers (category=institution) =====
-- Quelle: https://www.staatsoper.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Bayerische%20Staatsoper%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('bayerische-staatsoper', 'Bayerische Staatsoper', 'Staatliches Opernhaus mit Opern-, Konzert-, Ballett- und Ausbildungsangebot.', 'https://www.staatsoper.de/', 'besucher@staatsoper.de');
-- Quelle: https://www.br.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=BR-Klangk%C3%B6rper%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('br-klangkoerper', 'BR-Klangkörper', 'Dachmarke für BRSO, BR-Chor und Münchner Rundfunkorchester.', 'https://www.br.de/', null);
-- Quelle: https://www.gasteig.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Gasteig%20M%C3%BCnchen%20GmbH%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('gasteig-muenchen-gmbh', 'Gasteig München GmbH', 'Städtische Kulturinstitution und Betreiberin der Gasteig-Standorte.', 'https://www.gasteig.de/', 'kommunikation@gasteig.de');
-- Quelle: https://hmtm.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Hochschule%20f%C3%BCr%20Musik%20und%20Theater%20M%C3%BCnchen%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('hochschule-fuer-musik-und-theater-muenchen', 'Hochschule für Musik und Theater München', 'Staatliche Hochschule für Musik, Theater und Forschung mit Konzerten und Opernproduktionen.', 'https://hmtm.de/', null);
-- Quelle: https://www.muenchenerbiennale.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchener%20Biennale%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('muenchener-biennale', 'Münchener Biennale', 'Internationales Festival für neues Musiktheater, im zweijährigen Turnus.', 'https://www.muenchenerbiennale.de/', null);
-- Quelle: https://www.hoertnagel.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchener%20Konzertdirektion%20H%C3%B6rtnagel%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('muenchener-konzertdirektion-hoertnagel', 'Münchener Konzertdirektion Hörtnagel', 'Privater Konzertveranstalter mit langjährigem Klassikprogramm.', 'https://www.hoertnagel.de/', null);
-- Quelle: https://www.muenchner-dommusik.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Dommusik%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('muenchner-dommusik', 'Münchner Dommusik', 'Kirchenmusikalische Institution der Frauenkirche mit Domchor, Mädchenkantorei und Domsingknaben.', 'https://www.muenchner-dommusik.de/', null);
-- Quelle: https://www.muenchner-musikfest.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=M%C3%BCnchner%20Musikfest%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('muenchner-musikfest', 'Münchner Musikfest', 'Festival mit klassischem Konzertprogramm an mehreren Münchner Spielstätten.', 'https://www.muenchner-musikfest.de/', null);
-- Quelle: https://www.br.de/musica-viva/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=musica%20viva%20des%20BR%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('musica-viva-des-br', 'musica viva des BR', 'Konzertreihe des Bayerischen Rundfunks für zeitgenössische Musik.', 'https://www.br.de/musica-viva/', null);
-- Quelle: https://www.theaterakademie.de/  |  Bild-Recherche (Lizenz prüfen!): https://commons.wikimedia.org/w/index.php?title=Special:MediaSearch&type=image&search=Theaterakademie%20August%20Everding%20M%C3%BCnchen
insert into organizers (slug, name, description_de, website_url, contact_email) values ('theaterakademie-august-everding', 'Theaterakademie August Everding', 'Staatliche Ausbildungsinstitution für Musiktheater, Schauspiel, Musical und Regie.', 'https://www.theaterakademie.de/', null);

-- ===== Manuelle Review-Hinweise (nicht Teil der Inserts oben) =====
-- ensembles: 'Münchener Bach-Chor' (Excel) klingt wie dieselbe Institution wie das existierende 'Bachchor München' (Ensemble+Organizer) -- reine Substring-Prüfung fängt unterschiedliche Schreibweisen/Wortstellung nicht ab, manuell geprüft und hier von Hand vermerkt. Bitte vor dem Anwenden entscheiden: dasselbe (dann Zeile unten löschen) oder wirklich zwei verschiedene Chöre.
-- ensembles: 'Münchner Philharmoniker' existiert schon (Name-Match) -- übersprungen.
-- venues: 'Allerheiligen-Hofkirche' existiert schon (Name-Match) -- übersprungen.
-- venues: 'Dom zu Unserer Lieben Frau' NICHT übersprungen, aber ähnlich zu vorhandenem 'frauenkirche (dom zu unserer lieben frau)' -- bitte manuell prüfen ob dasselbe.
-- venues: 'Herkulessaal der Residenz' existiert schon (Name-Match) -- übersprungen.
-- venues: 'Isarphilharmonie' existiert schon (Name-Match) -- übersprungen.
-- venues: 'Prinzregententheater' existiert schon (Name-Match) -- übersprungen.
-- venues: 'St. Michael' existiert schon (Name-Match) -- übersprungen.
-- organizers: 'Bayerische Staatsoper' existiert bereits als VENUE mit gleichem Namen -- NICHT automatisch übersprungen (unterschiedliche Tabelle/Bedeutung), bitte manuell prüfen ob als Organizer zusätzlich sinnvoll oder Duplikat der Institution ist.
